
use super::types::{NT_STATUS, PROCESS_ACCESS_RIGHTS, VIRTUAL_ALLOCATION_TYPE, PAGE_PROTECTION_FLAGS};

pub const IMAGE_NUMBEROF_DIRECTORY_ENTRIES: usize = 16;
pub const IMAGE_DOS_SIGNATURE: u16 = 23117u16;
pub const IMAGE_NT_SIGNATURE: u32 = 17744u32;
#[allow(dead_code)]
pub const IMAGE_NT_OPTIONAL_HDR32_MAGIC: u16 = 267u16;
pub const IMAGE_NT_OPTIONAL_HDR64_MAGIC: u16 = 523u16;

#[allow(dead_code)]
pub const PROCESS_VM_READ: PROCESS_ACCESS_RIGHTS = 16u32;
#[allow(dead_code)]
pub const PROCESS_VM_WRITE: PROCESS_ACCESS_RIGHTS = 32u32;
#[allow(dead_code)]
pub const PROCESS_ALL_ACCESS: PROCESS_ACCESS_RIGHTS = 2097151u32;

pub const STATUS_SUCCESS: NT_STATUS = 0i32;

pub const MEM_COMMIT: VIRTUAL_ALLOCATION_TYPE = 4096u32;
pub const MEM_RESERVE: VIRTUAL_ALLOCATION_TYPE = 8192u32;

pub const PAGE_READWRITE: PAGE_PROTECTION_FLAGS = 4u32;